version: "3.7"

volumes:
  db:
    name: voltaserve-db
  s3:
    name: voltaserve-s3
  search:
    name: voltaserve-search
  redis:
    name: voltaserve-redis
  redisinsight:
    name: voltaserve-redisinsight

services:
  db:
    container_name: voltaserve-db
    image: voltaserve/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: voltaserve
      POSTGRES_PASSWORD: voltaserve
    volumes:
      - db:/var/lib/postgresql/data
    restart: on-failure
  s3:
    container_name: voltaserve-s3
    image: minio/minio:RELEASE.2022-01-28T02-28-16Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: voltaserve
      MINIO_ROOT_PASSWORD: voltaserve
      MINIO_REGION: us-east-1
    volumes:
      - s3:/data
    command: server /data --console-address ":9001"
    restart: on-failure
  smtp:
    container_name: voltaserve-smtp
    image: bytemark/smtp
    ports:
      - "25:25"
    restart: on-failure
  search:
    container_name: voltaserve-search
    image: getmeili/meilisearch:v0.25.2
    ports:
      - "7700:7700"
    volumes:
      - search:/data.ms
  redis:
    container_name: voltaserve-redis
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: on-failure
  idp:
    container_name: voltaserve-idp
    image: voltaserve/idp
    build:
      context: ../voltaserve-idp
    depends_on:
      - db
      - search
      - s3
    ports:
      - "7000:7000"
    environment:
      - URL=http://localhost:7000
      - WEB_URL=http://localhost:3000
      - DATABASE_URL=postgresql://voltaserve:voltaserve@db:5432/voltaserve
      - SEARCH_URL=http://search:7700
      - S3_URL=http://s3:9000
      - SMTP_HOST=smtp
      - SMTP_PORT=25
    restart: on-failure
  api:
    container_name: voltaserve-api
    image: voltaserve/api
    build:
      context: ../voltaserve-api
    depends_on:
      - db
      - redis
      - s3
      - search
    ports:
      - "5000:5000"
    environment:
      - URL=http://localhost:5000
      - WEB_URL=http://localhost:3000
      - DATABASE_URL=postgresql://voltaserve:voltaserve@db:5432/voltaserve
      - S3_URL=s3:9000
      - SEARCH_URL=http://search:7700
      - REDIS_ADDR=redis:6379
      - SMTP_HOST=smtp
      - SMTP_PORT=25
    restart: on-failure
  ui:
    container_name: voltaserve-ui
    image: voltaserve/ui
    build:
      context: ../voltaserve-ui
      args:
        - API_URL=http://api:5000
        - IDP_URL=http://idp:7000
    depends_on:
      - idp
      - api
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    restart: on-failure
  adminer:
    container_name: voltaserve-adminer
    image: adminer:4.8.1
    ports:
      - 9090:8080
    restart: on-failure
  redisinsight:
    container_name: voltaserve-redisinsight
    image: redislabs/redisinsight:1.11.0
    ports:
      - "8001:8001"
    volumes:
      - redisinsight:/db
    restart: on-failure
